### ISSUE TITLE
The mqtt connection will be disconnected after locking the computer screen for 5 minutes. Is there any solution?

### ISSUE THREAD

**Issue by jmxiang** [mqttjs/MQTT.js#1577] opened 2023-02-10 02:00 UTC
The mqtt connection will be disconnected after locking the computer screen for 5 minutes. Is there any solution?

**Comment by jmxiang** [comment] 2023-02-10 02:02
The browser label will also be disconnected after being inactive for a period of time

**Comment by eye-c** [comment] 2023-02-16 00:44
are you setting a keepalive value?
http://www.steves-internet-guide.com/mqtt-keep-alive-by-example/

**Comment by jmxiang** [comment] 2023-02-16 01:27
> 你在设置保活值吗？ http://www.steves-internet-guide.com/mqtt-keep-alive-by-example/

yes, keepalive: 5,

**Comment by haoguangchuan** [comment] 2023-03-09 06:27
I also encountered this and tried to set the keepalive parameter, but it didn't work.

By looking through the materials and reading the MQTT source code, I feel like I've found the problem.

When browser tabs are switched to background or minimized, the browser delays or even stops the execution of setInterval. MQTT sends heartbeat packets through the **reinterval** library, which is implemented through setInterval.

When the browser is minimized or the TAB is switched to the background, the heartbeat sent by the MQTT to the server is delayed or stopped, and the abnormal heartbeat causes the MQTT to go offline. You don't reconnect until the page is activated again.

Solution: It is recommended to replace reinterval with **work-timer**, which will avoid the above situation. Even if the browser is switched to the background or minimized, the timer can still run normally.

**Comment by simonbuchan** [comment] 2023-06-01 02:01
> Solution: It is recommended to replace reinterval with **work-timer**, which will avoid the above situation. Even if the browser is switched to the background or minimized, the timer can still run normally.

I assume you mean `worker-timer`, which currently states:

> Chrome, Firefox and maybe others throttle the frequency at which they invoke those timers to a maximum of once per second in such a situation.

And some googling seems to support this as the situation. That certainly sounds like it should be sufficient rate for a keep-alive!

**Comment by LiuZiqi-dual** [comment] 2023-07-08 03:59
Does anyone have a perfect solution? It seems that this problem still exists so far

**Comment by robertsLando** [comment] 2023-07-10 07:18
Duplicate of #1257, please follow updates there

**Closed by robertsLando** 2023-07-10 07:18 UTC
