### ISSUE TITLE
After calling mqttClient.end() also client is trying to reconnect

### ISSUE THREAD

**Issue by sowmyasoora** [mqttjs/MQTT.js#579] opened 2017-03-30 10:23 UTC
I wanted to disconnect mqttClient when i am logging out of my application. To disconnect i am using mqttClient.end(). client is trying to reconnect even after calling mqttClient.end().

Thanks in advance

**Comment by mcollina** [comment] 2017-03-30 10:30
Can you please upload an example?

**Comment by sowmyasoora** [comment] 2017-03-30 11:23
@mcollina Thanks for reply.

I am trying to connect mqtt broker using user credentials once i logged into my app. Once after user session expired i am using mqttClient.end() to disconnect mqtt client. But still mqtt client is trying to reconnect. As user credentials are invalid by that time it never connects to broker. I wanted to stop reconnect once i force closed my mqtt connection. Please help me out how can i achieve this?

Is there any way i can set an option for retry count?

**Comment by mcollina** [comment] 2017-03-30 12:44
after you call `.end()`, it should not try to reconnect.

**Comment by sowmyasoora** [comment] 2017-04-03 17:40
Hi @mcollina , .end() is working fine. No worries. Its my mistake.  Thanks for your quick response.

I have another issue. When i am trying to connect to my MQTT broker if my server have more cookies (cookies size is around 950 bytes), not able to establish web socket connection with error "**failed: Connection closed before receiving a handshake response**". If cookies are less every thing was proper and working fine. Do you have any idea?

**Comment by mcollina** [comment] 2017-04-04 09:02
I'm closing this issue.
I do not know about the second error, it might be related to your application. Feel free to open another issue and attach a way to reproduce the problem.

**Closed by mcollina** 2017-04-04 09:02 UTC

**Comment by boneskull** [comment] 2017-10-03 16:18
> after you call .end(), it should not try to reconnect. I fear it's a bug, would you mind uploading an example so we can replicate?

I'm experiencing something like this; I'll try to isolate a reproducible case.

**Comment by boneskull** [comment] 2017-10-07 06:44
so [here](https://github.com/mqttjs/MQTT.js/blob/master/lib/client.js#L223):

```js
this.on('close', this._setupReconnect);
```

Calling `MqttClient#end()` will eventually result in the end of the client's `stream`, so when that happens, [this listener](https://github.com/mqttjs/MQTT.js/blob/master/lib/client.js#L276) fires:

```js
eos(this.stream, this.emit.bind(this, 'close'))
```

...which invokes `_setupReconnect`, which reconnects again...

**Comment by boneskull** [comment] 2017-10-07 06:45
Anyhow, I mentioned in #690 that a finite state machine might be in order to sort this out, because we have too many booleans flying around in here.

**Comment by boneskull** [comment] 2017-10-11 16:58
OK, after some digging, it's actually a problem in `async-mqtt`.  It seems that the promisifcation of `end()` can cause race conditions.  still working on an MCVE

**Comment by RangerMauve** [comment] 2017-10-11 17:44
@boneskull If this is an async-mqtt problem could you raise an issue there?

**Comment by boneskull** [comment] 2017-10-11 18:09
@RangerMauve I don't believe it's something a wrapper can work around.

**Comment by jungkumseok** [comment] 2018-04-05 20:29
Hi guys, first of all thanks for this awesome library :)

I'm not sure if this is a "bug" or is expected behaviour, but I observed the same effect while using the lib in an object-oriented way. I believe the effect is indeed caused by a race condition between the `mqtt.connect()` and `client.end()` calls. See example below:

```
var mqtt = require('mqtt');

function Pubsub(){
    this.client = mqtt.connect('mqtt://localhost');
    this.client.on('connect', function(ack){
        console.log('Connected!');
    });
}
Pubsub.prototype.end = function(){
    this.client.end(function(){
        console.log('Ended!');
    });
}

var pubsub = new Pubsub();
pubsub.end();
```

Running this example, almost all the time (100/100 times in my quick test) the `pubsub.end()` call will be processed before `mqtt.connect()` is "complete" since `mqtt.connect()` is asynchronous.
Although this may be the intended behaviour, would it be reasonable to assume that once the user has called `client.end()` on the `mqtt.Client` instance, she no longer wishes to reconnect? Implementation-wise handling this would be as trivial as setting a flag to indicate that the `Client` instance should permanently ignore `.reconnect()` calls.
But then again, the user could actually want to reconnect by explicitly calling `.reconnect()` after some other concurrent `.end()` call, and there would be no way for the `Client` instance to tell which call should be served first. Perhaps a function like `client.destroy()` that permanently "disables" the `Client` instance might be useful?

In certain unconventional use-cases, `Client` instances are created temporarily and thrown away afterwards. When trying to throw away these objects, a user would do something like `.end()` and then de-reference the `Client` object from an array or a dictionary to make it available for the GC. After the `Client` instance is de-referenced and is no longer required by the application, the `.reconnect()` may be called and keep a socket opened, leading to a memory leak.

**Comment by mike-sandstrom** [comment] 2021-08-10 21:02
any updates on this? I try ending my client after 3 reconnect attempts until the user manually trys to reconnect--which creates a new client but I still get errors of this destroyed client trying to reconnect over websocket

**Comment by shivamydv** [comment] 2021-10-18 06:18
Is there an update on this bug? Has it been fixed or is there any work around for this?
