### ISSUE TITLE
Publish fails silently if payload is too big.

### ISSUE THREAD

**Issue by spydmobile** [mqttjs/MQTT.js#1005] opened 2019-11-05 18:16 UTC
This code will work:
`mqttClient.publish("intellifire/ember/allfires", JSON.stringify(wildfires.slice(0, 2000)))`
this will fail silently and reconnect:
`mqttClient.publish("intellifire/ember/allfires", JSON.stringify(wildfires.slice(0, 2500)))`

**Comment by RangerMauve** [comment] 2019-11-05 18:36
Transferring this issue to the main MQTT.js repository since I don't think it's caused by the async layer.

**Comment by spydmobile** [comment] 2019-11-05 19:04
Hi I am sorry, I do not think this is caused by mqtt.js or the async layer, I went into my broker and configured a larger packet limit and it is now working. So unless you feel there is work to be done about the error, i think this was not really a bug....

**Comment by RangerMauve** [comment] 2019-11-05 19:39
Sweet, thanks for double checking! Hopefully this issue will help people figure their situation out when this comes up for them. 😁

**Closed by RangerMauve** 2019-11-05 19:39 UTC
