### ISSUE TITLE
Connect to unix socket

### ISSUE THREAD

**Issue by ralight** [mqttjs/MQTT.js#1040] opened 2020-02-06 12:03 UTC
Would you consider support for connecting to unix sockets? The use case is a local application wanting to connect to a local MQTT broker without having to create a network.

It looks like `lib/connect/unix.js` would be very similar to `tcp.js`, but with this sort of construct instead:

```
    unixpath = '/var/run/mqtt.socket'

    return net.createConnection(unixpath)
```

**Comment by mcollina** [comment] 2020-02-06 12:32
Definitely! I have no bandwidth to work on this, but I’ll be happy to review a PR
Il 6 feb 2020, 13:03 +0100, Roger Light <notifications@github.com>, ha scritto:

**Comment by ralight** [comment] 2020-02-11 10:41
Thanks, I'll take a look.

**Comment by ralight** [comment] 2022-03-31 17:05
I hadn't done any more because of this: https://github.com/mqttjs/MQTT.js/pull/1094 , but that has been closed now for some reason. It wasn't clear what to use as the URL prefix, otherwise I suspect it may have got further.

I've been using my own modified version just fine, I'd be happy for anyone to take this over.

**Comment by natcl** [comment] 2023-05-18 11:50
We're still interested in this!

**Comment by nik-sie** [comment] 2024-02-05 18:33
It's actually possible to connect to a `unix socket` right now.
Check this out:
```js
'use strict';
const mqtt = require('mqtt');
const cfg = { pathname: "/run/mosquitto/mosquitto.sock", username: "user", password: "pass" };
const client = mqtt.connect(cfg);
client.on('error', (err) => { if (err) { console.error(err); }; });
client.subscribe(['#'], { nl: true }, (err, granted) => { console.log("granted:", granted); });
client.on('message', (path, data, packet) => { console.log("mqtt_msg_in: ['%s']:(%d) '%s'", path, data.length, data.toString()); });
```

**Comment by robertsLando** [comment] 2024-02-06 08:32
I dunno how that code could work @nik-sie, the PR adding unix socket support has never been merged. Maybe the default tcp handler could work as it support sockets too

**Comment by nik-sie** [comment] 2024-02-06 14:27
@robertsLando, If you really want to use unix sockets, just try it, it works, I've been using it for a long time.
It works, since `MqttClient` uses node's native `net.createConnection()`call  under the hood, which accepts `path` option (if given) to create connection to an IPC.
The PR would only add convenience of using URLs, that it.

**Comment by nik-sie** [comment] 2024-04-25 19:10
@rockey2020, there should NOT be any prefixes to the path, remove the `unix://` part.
Also, make sure your mqtt client actually has read+write access to the socket file.

**Comment by nik-sie** [comment] 2024-04-25 20:36
I did a quick test and, apparently, compiled ts -> js output indeed changed drastically, so old simple method doesn't work anymore.
Here is how it works now:
```js
'use strict';

const net = require('node:net');
const mqtt = require('mqtt');

function streamBuilder() { return net.createConnection({ path: "/run/mosquitto/mosquitto.sock" }); };
function msg_recv(path, data, packet) { console.log("mqtt_msg_in: ['%s']:(%d) '%s'", path, data.length, data.toString()); };

const client = new mqtt.Client(streamBuilder, { username: "user", password: "pass" });
client.on('error', (err) => { if (!err) { return; }; console.error(err); client.end(); });
client.on('connect', (conn_evt) => {
    console.log("mqtt: connected. Subscribing...");
    client.subscribe(['#'], { nl: true }, (err, granted) => { console.log("granted:", granted); });
});
client.on('message', msg_recv);
```

**Comment by robertsLando** [comment] 2024-04-26 08:16
I think the problem is the `path` argument is not passed down correctly to the `createConnection`, does someone wants to submit a PR for that?

**Closed** 2024-04-26 08:19 UTC

**Comment by drdaeman** [comment] 2024-05-05 20:25
May I suggest reopening this (or should I create a new issue?) for URI-based support, e.g. `mqtt:///run/mosquitto/mosquitto.socket`, `mqtt+unix:///run/mosquitto/mosquitto.socket`, or something similar?

The idea is that it would allow various projects (I'm thinking about Zigbee2MQTT, which currently doesn't seem to have a way to specify `path` in their configuration file) that use this library to automagically start supporting connecting to UNIX sockets without any code changes besides, of course, bumping their mqtt.js dependency version.

Thanks!

**Comment by robertsLando** [comment] 2024-05-06 06:49
@drdaeman want to submit a PR?
