### ISSUE TITLE
React Native: Cannot find entry file MqttClient

### ISSUE THREAD

**Issue by pewh** [mqttjs/MQTT.js#443] opened 2016-08-03 02:58 UTC
Hi, this is a continue from https://github.com/mqttjs/MQTT.js/issues/442

After I can get module loaded, I'm doing `const client = mqtt.connect('ws://192.168.58.1:8080')`. But I get error on console `NotFoundError: Cannot find entry file MqttClient`. I can't figure out how to resolve this issue. For the info, I've successfully testing MQTT server (using websocket) with chrome plugin MQTTLens, so I think there's no issue on MQTT broker itself.

**Edit:**
I compile browser version with `webpack mqtt.js ./client.js --output-library mqtt --output-library-target commonjs2`

**Comment by RangerMauve** [comment] 2016-08-03 13:36
Try compiling `./lib/connect/index.js` instead. That's the entry point that Browserify uses.

**Comment by RangerMauve** [comment] 2016-08-03 13:38
Also, have it ignore the "fs", "tls", and "net". This is all specified in the [browser field of the package.json](https://github.com/mqttjs/MQTT.js/blob/master/package.json#L42). Browserify should be doing this automagically, but I guess you'll need to fiddle with React Native or Webpack or whatever it is that you're using.

**Comment by pewh** [comment] 2016-08-03 14:13
Hi, @RangerMauve.

I've trying with: `webpack .lib/connect/index.js ./client.js --output-library mqtt --output-library-target commonjs2`, and it still show same error.

And I'm still confused what method should I use between browserify & webpack. I have test with browserify, compile with command `browserify mqtt.js -s mqtt > browserMqtt.js` or `browserify ./lib/connect/index.js -s mqtt > browserMqtt.js` show same error that it needs 'stream' & 'buffer' nodejs native module.

**Comment by RangerMauve** [comment] 2016-08-03 14:50
Where are you running your webpack command from? Is it from within the `mqtt` folder with the source code for the client? If not, then you might want to make a small JS file which just contains

```
module.exports = require("mqtt/lib/connect/index.js);
```

and build that instead.

**Comment by pewh** [comment] 2016-08-03 16:08
This is what I've done:

```
npm i mqtt -S
cd node_modules/mqtt
webpack ./lib/connect/index.js ./client.js --output-library mqtt --output-library-target commonjs2
```

I guess I'm doing wrong :/

What is the file name for that small JS? index.js?

**Comment by RangerMauve** [comment] 2016-08-03 17:37
So, how are you then consuming the bundle you're creating from the rest of your code?

Ideally, your app's React Native code should just be calling `require("mqtt")`, and the React Native build tools should automatically require and bundle it for you.

**Comment by pewh** [comment] 2016-08-04 04:07
After `client.js` was created inside `node_modules/mqtt`, I call `import mqtt from 'mqtt/client` on React Native. There's no problem so far. But when I call `const client = mqtt.connect('ws://localhost:8080)`, I get an error `Could not determine host. Specify host manually`.

But if I'm just calling `require('mqtt')`, it throws an error

**Comment by RangerMauve** [comment] 2016-08-04 04:14
Try to import from `mqtt/lib/connect/index.js`

**Comment by pewh** [comment] 2016-08-04 05:32
Hello @RangerMauve , I get an error `Requiring unknown module "events"` on RN.
However, I'm still confused about browserify because it's the first time I use that. So I have a question.

1. I'm compiling with webpack `webpack ./lib/connect/index.js ./client.js --output-library mqtt --output-library-target commonjs2`, and file `node_modules/mqtt/client.js` will be created
2. On RN code, I just import `mqtt/lib/connect/index.js`, but why I need to compile to `client.js` if I don't use `client.js`?

**Comment by RangerMauve** [comment] 2016-08-04 13:51
You don't need to compile the client with webpack if you're importing it from within your react-native project. Do you think you could post the commands you're running to build your project, as well as a snippit of the code you're using importing / using the module?

Also, I think the issue is that React-Native is missing a bunch of Node standard modules. You can install pure JS versions from NPM. For instance to fix your current error you could use `npm install -s events` which would install the [events module](https://www.npmjs.com/package/events)

**Comment by mcollina** [comment] 2016-09-01 15:50
Closing as I think it was fixed.

**Closed by mcollina** 2016-09-01 15:50 UTC
