### ISSUE TITLE
v5 support

### ISSUE THREAD

**Issue by muka** [mqttjs/MQTT.js#812] opened 2018-05-02 08:27 UTC
Hi
I am wondering if anybody has started taking a look at MQTT v5 specs. Is there someone working on that or would like to work on the implementation?

A *growing* list of features for the v5 support (help is welcome to make it more precise)

- [ ] Properties as header variables
- [ ] Error reason code and message
- [ ] Flow control for QoS 1/2
- [ ] Request / Response pattern
- [ ] Shared Subscriptions
- [ ] Session management
- [ ] Publication expiry interval
- [ ] Improved AUTH support 
- [ ] Last Will and Testament
- [ ] keep alive timeout in CONNACK
- [ ] CONNECT with empty user field
- [ ] Provide client-id in CONNACK
- [ ] Maximum QoS from CONNACK and reason code on disconnect
- [ ] Use topic aliases over full topic in messages

A few resources to crunch:

- [Specification](http://docs.oasis-open.org/mqtt/mqtt/v5.0/mqtt-v5.0.html)
- [New features explained](https://dzone.com/articles/mqtt-v5-what-is-on-the-way)

See also this issue for reference https://github.com/mcollina/aedes/issues/194

Thanks

**Comment by RangerMauve** [comment] 2018-05-02 14:09
Duplicate of https://github.com/mqttjs/MQTT.js/issues/651

**Closed** 2018-05-02 14:10 UTC

**Comment by muka** [comment] 2018-05-02 14:30
@RangerMauve fair, see you on #651 then :)
