### ISSUE TITLE
Browserified MQTT.js fails to keep connection on IE10

### ISSUE THREAD

**Issue by sandro-k** [mqttjs/MQTT.js#333] opened 2015-10-14 14:35 UTC
Hey I am trying to get [mqtt-elements](https://github.com/mqttjs/mqtt-elements) with MQTT.js to work with IE10. I have an old bundle of [MOWS](https://github.com/sandro-k/mqtt-connection/blob/master/mows/mows.js) that is working with IE10.

 To locate the problem I am using a browserified version of MQTT.js without any Webcomponent/ Polymer add-ons. The bundled version of MQTT.js is build with 

```
browserify ../node_modules/mqtt/mqtt.js --standalone mqttjs > bundle.js
```

when running 
```
var client = mqttjs.connect("ws://localhost:3005",  options);
```

in Chrome the MQTT connection is established and I get the following log on the broker
```
client connected (client=mqttjs_test)
```
after that I can subscribe/ publish using the console. Running the same code in IE10 actually connects the client to the MQTT-Broker and I get the following log message on the broker:

```
client connected
```
It looks like the client is connecting without a `clientId` to the broker. I am not able to subscribe or publish any messages. The payload of both `CONNECT ` packets from Chrome and IE10 is identical. 

Right now I have no clue what is broken withe the build. 

A VM with IE10 can be obtained at https://dev.modern.ie/tools/vms/.

Thanks Sandro

**Comment by mcollina** [comment] 2015-10-14 14:42
Which broker are you using?

MQTT 3.1.1 supports clients without a clientId.

Are MQTT.js broker tests passing on IE10?

Also you should have a look at checking mqtt-packet tests pass fine in the
browser.
Il giorno mer 14 ott 2015 alle 16:35 Sanndro <notifications@github.com> ha
scritto:

**Comment by sandro-k** [comment] 2015-10-14 15:02
On my local machine I am using mosca and testing it against a Mosquitto instance. 

Which is the right test to run test/browser/test.js? How would you run it in the Browser?

**Comment by mcollina** [comment] 2015-10-14 15:05
I'm from my mobile now. Look into package.json, there should be a script
defined
Il giorno mer 14 ott 2015 alle 17:02 Sanndro <notifications@github.com> ha
scritto:

**Comment by sandro-k** [comment] 2015-10-14 15:11
Found the command :+1: 

4 Test are failing

```

MqttClient :: specifying a port :: should publish and subscribe
timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.

timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.

timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.


MqttClient :: specifying a port and host :: should connect
timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.

timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
done() invoked with non-Error: [object Event]

done() invoked with non-Error: [object Event]


MqttClient :: specifying a URL :: should connect
timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.

timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
done() invoked with non-Error: [object Event]

done() invoked with non-Error: [object Event]


MqttClient :: specifying a URL with a path :: should connect
timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.

timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
```

**Comment by mcollina** [comment] 2015-10-14 15:18
Possibly something in lib/connect/* is wrong for IE 10, at least regarding
the connect arguments. Put some console.log in there, and try understanding
where the problem is. Comparing it with chrome might help.
Il giorno mer 14 ott 2015 alle 17:11 Sanndro <notifications@github.com> ha
scritto:

**Comment by mcollina** [comment] 2016-09-01 15:45
Was this fixed?

I'm closing for now, as there seem to be no interest in supporting IE10, and time is passing by.

**Closed by mcollina** 2016-09-01 15:45 UTC

**Comment by sandro-k** [comment] 2016-09-02 07:01
This is not fixed yet, but currently we are not getting any IE10 traffic and therefore no errors. If the need to support IE10 pops up again I will reopen this issue.
