### ISSUE TITLE
Mqtt disconnects on inactive browser tab (Chrome)

### ISSUE THREAD

**Issue by ahmer-mt** [mqttjs/MQTT.js#1608] opened 2023-05-26 07:19 UTC
**Overview:**
I am currently using vernemq as a MQTT broker and mqttjs in my React App. However, I am encountering an issue where the client gets disconnected after approximately 30-60 seconds of inactivity when my tabs are inactive. Fortunately, the client automatically reconnects once I return to the tab. Despite attempting manual reconnection mechanisms, such as calling the client.reconnect method on close events, I have been unable to resolve the issue.

**Steps to Reproduce:**

1. Set up a React App using mqttjs as the MQTT client library.
2. Connect the client to the vernemq MQTT broker.
3. Open the app in a web browser with multiple tabs.
4. Navigate to a different tab and leave it inactive for approximately 30-60 seconds.
5. Return to the tab with the React App and observe the client's disconnection.
6. Notice that the client automatically reconnects upon returning to the tab.

**Expected Behaviour:**
The MQTT client should remain connected to the vernemq broker even when the tab is inactive for a certain period of time. It should not disconnect automatically and should maintain a consistent connection.

**Actual Behavior:**
The MQTT client gets disconnected after approximately 30-60 seconds of inactivity when the tab is inactive. However, it automatically reconnects once the tab becomes active again.

**Additional Information:**

- I have attempted to manually reconnect by calling the client.reconnect method on close events, but it does not resolve the issue.
- I have verified that the issue is specific to the combination of vernemq as the MQTT broker and mqttjs as the client library.
- I have tested this behavior on multiple browsers and observed the same issue consistently.

**Environment:**

- MQTT Broker: vernemq
- MQTT Client Library: mqttjs
- Browser: Chrome
- Version(s): mqtt 3.0.0 and vernemq 1.11.0

**Additional Notes:**
Please let me know if you need any further information or if there are any known workarounds or solutions to address this issue.

**Comment by velialan** [comment] 2023-06-07 21:29
I have same problem. I am using https://github.com/eclipse/paho.mqtt.javascript on React. No problems for now.

**Comment by swapnonil-b** [comment] 2023-07-04 16:47
Can confirm this is not specifically an issue with the broker, but with just the MQTT.js library itself. Since I have the same issue with emqx, on a react app.

**Comment by robertsLando** [comment] 2023-07-05 06:16
Anyone that would like to send a PR to fix this?

**Comment by robertsLando** [comment] 2023-07-10 07:16
Duplicate of #1257, please follow updates there

**Closed by robertsLando** 2023-07-10 07:16 UTC
