### ISSUE TITLE
it seems that the mqtt client has forgotten to send pingreq

### ISSUE THREAD

**Issue by Karl-Sparticle** [mqttjs/MQTT.js#1576] opened 2023-02-08 07:27 UTC
Hi,
I got the event 'offline'. It seems that the mqtt client has forgotten to send pingreq.

Version: 
"mqtt": "4.2.1"
"react": "^16.9.0",

Log:
![image](https://user-images.githubusercontent.com/95554023/217460708-20d60f0d-90a5-423f-a25f-44d5ef08d50e.png)

Code:
```
import ReactDOM from 'react-dom';
import React from 'react';
import mqtt from 'mqtt';

const App = () => {
  const [connected, setConnected] = React.useState(false);
  const [clientId, setClientId] = React.useState('');
  const [client, setClient] = React.useState(null);

  const addLog = (time, message, event) => {
	let log = `${time} | ${event} | ${message}`;
      console.log(log);

      if (event === 'connect') {
        document.getElementById("text").innerHTML += `<h3 style="color:green">${log}</h3>`;
      }else if (event === 'offline') {
        document.getElementById("text").innerHTML += `<h3 style="color: red">${log}</h3>`;
      }else {
      	document.getElementById("text").innerHTML += `<p>${log}</p>`;
      }
    }

    const getMqttOptions = async () => {
        // fetch... username and password
        const data = await resp.json();
        if (!data.success) {
            throw new Error("Cannot get mqtt info for connecting")
        }

        return data.result;
    }

    const initClient = (result) => {
        setClientId(result.clientId);

        var client = mqtt.connect(result.wsUrl, {
            username: result.username,
            password: result.password,
            clientId: result.clientId,
            keepalive: 15
        });

        client.on('connect', () => {
        setConnected(true);
        addLog(new Date().toLocaleString(), 'Connected to MQTT broker', 'connect');
        });
        
        client.on('reconnect', () => {
        addLog(new Date().toLocaleString(), 'Reconnecting...', 'reconnect');
        });
        
        client.on('close', () => {
        addLog(new Date().toLocaleString(), 'Closing connection...', 'close');
        });
        
        client.on('offline', () => {
        addLog(new Date().toLocaleString(), 'Offline...', 'offline');
        });
        
        client.on('error', (error) => {
            addLog(new Date().toLocaleString(), 'Error: ' + JSON.stringify(error), 'error');

            if (error.code === 4) {
                client.end();
                setClient(null);
                console.log('The client has ended for username or password error');
            }

        });
        
        client.on('message', (topic, message, packet) => {
        addLog(new Date().toLocaleString(), `Received message on topic "${topic}": ${message.toString()}`, 'message');
        });
        
        client.on('packetsend', (packet) => {
        addLog(new Date().toLocaleString(), 'Sending Packet: ' + JSON.stringify(packet), 'packetsend');
        });
        
        client.on('packetreceive', (packet) => {
        addLog(new Date().toLocaleString(), 'Received Packet: ' + JSON.stringify(packet), 'packetreceive');
        });
        
        client.on('end', () => {
        addLog(new Date().toLocaleString(), 'Ending connection...', 'end');
        });
        
        client.on('disconnect', (packet) => {
        addLog(new Date().toLocaleString(), 'Disconnected with packet: ' + JSON.stringify(packet), 'disconnect');
        });

        setClient(client);
    }

    React.useEffect(async () => {
        const result = await getMqttOptions();
        initClient(result);
  }, []);

  return (
    <div>
      <p>{new Date().toLocaleString()} | {clientId} | {connected ? 'Connected to MQTT broker' : 'Connecting to MQTT broker...'}</p>

<hr/>
 <div id='text'></div>
    </div>
  );
};

ReactDOM.render(<App />, document.getElementById('root'));
```

**Comment by robertsLando** [comment] 2023-07-10 07:18
Duplicate of #1257, please follow updates there

**Closed by robertsLando** 2023-07-10 07:18 UTC
