### ISSUE TITLE
error in iOS15 when connect

### ISSUE THREAD

**Issue by superAlexShen** [mqttjs/MQTT.js#1326] opened 2021-09-23 09:05 UTC

**Comment by YoDaMa** [comment] 2021-09-27 16:02
this is super vague I don't really know what to do with it.

We don't officially support iOS. Could be a consideration for vNext work. if you're an iOS developer and know how to ensure compatibility, let me know. 

For now closing the issues.

**Closed by YoDaMa** 2021-09-27 16:02 UTC

**Comment by andrewleong** [comment] 2021-09-28 09:25
I'm facing the same issue on IOS 15, does anyone have a workaround for this? I'm using webkit to load the client side from the IOS app.

**Comment by andrewleong** [comment] 2021-09-30 01:09
I have found the cause to the problem. In IOS 15.0, the safari experimental feature "NSURL Session WebSocket" was enabled by default. You need to disable it in safari settings. Hope this helps anyone.

**Comment by YoDaMa** [comment] 2021-10-04 14:15
@andrewleong thanks for providing that tip!

**Comment by rock123gh** [comment] 2021-10-30 02:31
@andrewleong 同样问题，已解决，NSURL Session WebSocket IOS 14.0以下都是默认不开启，IOS 15.0默认都是开启，就是每个IOS 15.0都要设置一下，比较麻烦。 不过还是非常感谢
