### ISSUE TITLE
Uncaught Error 'cb is not a function'

### ISSUE THREAD

**Issue by yetifortrees** [mqttjs/MQTT.js#569] opened 2017-03-17 05:30 UTC
Since the most recent release, I have been having issues with the library crashing.
This:
```
TypeError: cb is not a function
    at Store.del (/usr/src/app/node_modules/mqtt/lib/store.js:77:5)
    at MqttClient._handleAck (/usr/src/app/node_modules/mqtt/lib/client.js:865:26)
    at MqttClient._handlePacket (/usr/src/app/node_modules/mqtt/lib/client.js:293:12)
    at process (/usr/src/app/node_modules/mqtt/lib/client.js:242:12)
    at Writable.writable._write (/usr/src/app/node_modules/mqtt/lib/client.js:252:5)
    at doWrite (/usr/src/app/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:347:64)
    at writeOrBuffer (/usr/src/app/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:336:5)
    at Writable.write (/usr/src/app/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:274:11)
    at TLSSocket.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)

```
is the stack-trace from the crashing. As best I can tell, this is coming from somewhere the cb is checked for existence, but isn't a function as expected. This has only been happening since the most recent 2.4.0 release to the best of my knowledge.

**Comment by mcollina** [comment] 2017-03-17 07:35
@yetifortrees do you have a script to reproduce?

**Comment by yetifortrees** [comment] 2017-03-17 13:47
@mcollina So unfortunately the code is being used in a relatively large project and I can't get the error to trace back to anywhere in my code, so not currently. I can however try and write some smaller test scripts to replicate the issue, and let you know what I find.

**Comment by sublimator** [comment] 2017-03-18 05:15
I vaguely recall a similar issue, when using the @types/mqtt typescript bindings which led me to misuse the (subscribe??) function with a non conforming function overload ( yeah, yeah, JS lol ). Perhaps there's been some subtle changes ... since 1.x or a more recent release ... I've only used 2.x

Check that you're supplying the callbacks and options objects in the right order to subscribe/publish etc ... Read the source code for said functions for the ultimate truth :)  ( to check if the docs are wrong )

```js
MqttClient.prototype.subscribe = function () {
  var packet
  var args = Array.prototype.slice.call(arguments)
  var subs = []
  var obj = args.shift()
  var callback = args.pop() || nop
  var opts = args.pop()
  var invalidTopic
  var that = this

  if (typeof obj === 'string') {
    obj = [obj]
  }

  if (typeof callback !== 'function') {
    opts = callback
    callback = nop
  }
```

**Comment by OmgImAlexis** [comment] 2020-05-11 08:57
Since this seems version dependant I'm closing this. If this is still an issue with the latest version please comment or open a new issue.

**Closed by OmgImAlexis** 2020-05-11 08:57 UTC
