### ISSUE TITLE
Client is unsubscribed when disconnected 

### ISSUE THREAD

**Issue by vallettea** [mqttjs/MQTT.js#352] opened 2015-11-23 16:18 UTC
Here is a code to reproduce what i mean:

```
"use strict";

var mqtt = require('mqtt');

var PRIVATE = require('./PRIVATE.json');

var simId = "0000"

var client = mqtt.connect('mqtt://' + PRIVATE.host + ':' + PRIVATE.port,
    {
        username: simId,
        password: PRIVATE.mqttToken,
        clientId: simId,
        keepalive: 1,
        clean: false,
        // Do not set to a value > 29 until this bug is fixed : https://github.com/mqttjs/MQTT.js/issues/346
        reconnectPeriod: 1000 * 1
    }
);


client.on('connect', function(){
    console.log('connected to the server. ID :', simId);
});

client.on('message', function(topic, message) {
    // message is a Buffer
    console.log("data received : " + message.toString());
});

client.on("error", function(error) {
    console.log("ERROR: ", error);
});

client.on('offline', function() {
    console.log("offline");
});

client.on('reconnect', function() {
    console.log("reconnect");
});
    

setTimeout(function(){
   client.subscribe('test'); 
}, 3000)

//start sending
var i = 0;
setInterval(
    function(){
        var message = i.toString();
        console.log("sending ", message)
        client.publish("test", message, {qos: 1}, function(){
            console.log("sent ", message)
        });
        i += 1;
    },
3000)
```

It outputs:

```
sending  0
sent  0
data received : 0
sending  1
sent  1
data received : 1
sending  2
offline
reconnect
sending  3
sending  4
sending  5
sending  6
sending  7
sending  8
sending  9
sending  10
sending  11
sending  12
offline
reconnect
connected to the server. ID : 0000
sent  3
sent  4
sent  5
sent  6
sent  7
sent  8
sent  9
sent  10
sent  11
sent  12
sending  13
sent  13
sending  14
sent  14
sending  15
sent  15
```

this outputs suggests that once disconnected, the client reconnects and sends the message which is received by another client listening to the subject (i've checked). however the client seems to not be subscribed to the topic `test` anymore.

Is this normal, or I am missing something ?
thx

**Comment by RangerMauve** [comment] 2015-11-23 16:21
You are correct that the client doesn't re-subscribe upon reconnecting, though I'm pretty sure this is by design. I usually wrap over the client with something that keeps track of subscriptions and re-subs on the `connect` event.

**Comment by mcollina** [comment] 2015-11-23 19:34
Actually we plan to add it in https://github.com/mqttjs/MQTT.js/issues/166. Would you like to send a PR?

**Comment by vallettea** [comment] 2015-11-25 10:54
I'm looking into this to try a PR with @mcollina proposal of https://github.com/mqttjs/MQTT.js/issues/166#issuecomment-70410891

However, my sessionPresent is always false even if I specify a `clientId` and 

```
connected to the server. ID : 0000 { cmd: 'connack',
  retain: false,
  qos: 0,
  dup: false,
  length: 2,
  topic: null,
  payload: null,
  sessionPresent: false,
  returnCode: 0 }
offline
reconnect
offline
reconnect
connected to the server. ID : 0000 { cmd: 'connack',
  retain: false,
  qos: 0,
  dup: false,
  length: 2,
  topic: null,
  payload: null,
  sessionPresent: false,
  returnCode: 0 }
``` 

with the folowing options:

```
    {
        username: "unique",
        password: "xxxx",
        clientId: "unique",
        keepalive: 1,
        clean: false,
        reconnectPeriod: 1000 * 3
    }
```

**Comment by mcollina** [comment] 2015-11-25 11:05
Which broker are you using?

**Comment by vallettea** [comment] 2015-11-25 11:05
mosca

**Comment by mcollina** [comment] 2015-11-25 11:09
Which version? It should be handled.

**Comment by vallettea** [comment] 2015-11-25 11:13
I use it embeded in a nodejs program, version `"mosca": "^0.32.0",` 

with the following settings

```
var pubsubsettings = {
  type: 'redis',
  redis: require('redis'),
  db: 12,
  port: process.env.REDIS_PORT_6379_TCP_PORT,
  return_buffers: true, // to handle binary payloads
  host: process.env.REDIS_PORT_6379_TCP_ADDR
};

var moscaSettings = {
  port: 1883,
  backend: pubsubsettings
};
```

**Comment by mcollina** [comment] 2015-11-25 11:15
You also need to configure a persistence to enable the offline storage: https://github.com/mcollina/mosca/wiki/Mosca-advanced-usage#redis-persistence-options.

**Comment by vallettea** [comment] 2015-11-25 11:23
You mean that for now I don't store all messages ? what is redis for then ?
How to configure the offline storage ? I could also clarify the docs here.

**Comment by mcollina** [comment] 2015-11-25 11:28
Redis for "backend" is used for running multiple brokers (HA), You need to configure a persistence to enable offline: https://github.com/mcollina/mosca/blob/master/test/server_redis.js#L34-L36. The options are in the above wiki page. Yeah.. a nice pass on the docs will be nice :).

**Comment by vallettea** [comment] 2015-11-25 14:21
I've configured the offline storage like so for mosca:

```
var pubsubsettings = {
  type: 'redis',
  redis: require('redis'),
  db: 12,
  host: process.env.REDIS_PORT_6379_TCP_ADDR,
  port: process.env.REDIS_PORT_6379_TCP_PORT,
  return_buffers: true
};

var moscaSettings = {
  port: 1883,
  backend: pubsubsettings,
  persistence: {
    factory: mosca.persistence.Redis,
    host: process.env.REDIS_PORT_6379_TCP_ADDR,
    port: process.env.REDIS_PORT_6379_TCP_PORT,
  }
};
```

but i still get a `sessionPresent: false` after reconnexion

**Comment by mcollina** [comment] 2015-11-25 14:26
Are you subscribing to anything with QoS = 1? If you have no offline subscription, there is nothing to restore.

**Comment by vallettea** [comment] 2015-11-25 14:28
ok, yes i see what you mean.
But concerning the earlier problem of having a `sessionPresent: false` even after reconnect you think it si a pb with mosca or mqtt ?

**Comment by mcollina** [comment] 2015-11-25 14:40
Try with mosquitto (one of the latest). It might be a problem with Mosca (which I would need to track down).

**Comment by mcollina** [comment] 2015-11-25 14:41
or mosca standalone.

In the code above:

```
setTimeout(function(){
   client.subscribe('test'); 
}, 3000)
```

should be:

```
setTimeout(function(){
   client.subscribe('test', { qos: 1 }); 
}, 3000)
```

**Comment by vallettea** [comment] 2015-11-26 08:07
indeed the previous test works perfectly on `mqtt://test.mosquitto.org:1883` so there is a problem with mosca. I opened https://github.com/mcollina/mosca/issues/376 on mosca

**Comment by mcollina** [comment] 2016-09-01 15:39
Closing.

**Closed by mcollina** 2016-09-01 15:39 UTC
