### ISSUE TITLE
Large messages cause disconnects

### ISSUE THREAD

**Issue by damoncasale** [mqttjs/MQTT.js#1493] opened 2022-06-09 21:33 UTC
I've been pulling my hair out over this for a couple of days, now.

Trying to receive base64-encoded images (about 500k before base64-encoding) via MQTT over websockets.  I want to stream the images from the server to the browser, to display via data URIs.

Unfortunately, size seems to be some kind of limiting factor in receiving these messages.  I have a server-side test script that uses Paho MQTT to receive these messages over websockets, and it works fine.  However, using mqtt.js over websockets leads to repeated disconnects before the large message finishes being received, and I never get any of the large messages.  I'm able to get small messages (on the order of a few kilobytes) just fine.

What could be causing these repeated disconnects, and how do I fix it?

This is my current config:

```
const clientId = 'mqttjs_browser_' + Math.random().toString(16).substr(2, 8)
const client  = mqtt.connect(MQTT_URL, {
  clientId: clientId,
  username: MQTT_USER,
  password: MQTT_PASSWORD,
  keepalive: 150,
  protocolId: 'MQTT',
  protocolVersion: 4,
  clean: true,
  reconnectPeriod: 1000,
  connectTimeout: 150 * 1000,
  properties: {
    maximumPacketSize: 10485760,
    receiveMaximum: 10485760
  },
  will: {
    topic: 'WillMsg',
    payload: 'Connection Closed abnormally..!',
    qos: 0,
    retain: false
  },
  rejectUnauthorized: false
})

client.on('connect', async function () {
  try {
    console.log('client connected:' + clientId)
    let topics = ['station1/cameracapture/cam1', 'station1/cameracapture/cam2', 'station1/cameracapture/cam3', 'station1/cameracapture/cam4', 'station1']
    client.subscribe(topics, { qos: 0 })
  } catch (e) {
    // Do nothing
  }
})

client.on('message', function (topic, message) {
  try {
    console.log('Received message');
    let data = JSON.parse(message.toString('utf8'))
    ...
  } catch (e) { ... }
})

```
Any ideas?  Could I be sending too much data too quickly for websockets in my browser to keep up?  I'm sending four roughly 500k images every 30 seconds.

**Comment by robertsLando** [comment] 2023-07-31 15:42
Duplicate of #655

**Closed by robertsLando** 2023-07-31 15:42 UTC
